### ISSUE TITLE
使用Let`s Encrypt证书反代icalingua-bridge-oicq会提示证书过期

### ISSUE THREAD

**Issue by Dreagonmon** [Icalingua/Icalingua#261]
同样使用nginx反代，使用http连接服务器的时候可以正常连接，而改成https则会提示WebSocket Error.
浏览器直接访问服务器的http和https，都会显示 “Cannot GET /” 页面（应该是正常表现？），https配置应该没有问题。

Icalingua版本: 2.3.2， AppImage版本, amd64

错误信息:
```
./Icalingua-2.3.2.AppImage 
libva error: /usr/lib/dri/i965_drv_video.so init failed
[1874:1008/085453.505657:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
icalingua> (node:1819) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `icalingua --trace-warnings ...` to show where the warning was created)
Error: websocket error
    at f.onError (/tmp/.mount_Icalinp7xzg8/resources/app.asar/dist/electron/main.js:5:139542)
    at T.ws.onerror (/tmp/.mount_Icalinp7xzg8/resources/app.asar/dist/electron/main.js:315:160757)
    at T.u (/tmp/.mount_Icalinp7xzg8/resources/app.asar/dist/electron/main.js:309:5041)
    at T.emit (node:events:394:28)
    at T.emit (node:domain:470:12)
    at ClientRequest.<anonymous> (/tmp/.mount_Icalinp7xzg8/resources/app.asar/dist/electron/main.js:275:14262)
    at ClientRequest.emit (node:events:394:28)
    at ClientRequest.emit (node:domain:470:12)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:394:28) {
  type: 'TransportError',
  description: a {
    target: T {
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      _binaryType: 'nodebuffer',
      _closeCode: 1006,
      _closeFrameReceived: false,
      _closeFrameSent: false,
      _closeMessage: '',
      _closeTimer: null,
      _extensions: {},
      _protocol: '',
      _readyState: 2,
      _receiver: null,
      _sender: null,
      _socket: null,
      _bufferedAmount: 0,
      _isServer: false,
      _redirects: 0,
      _url: 'wss://********(hide)/socket.io/?EIO=4&transport=websocket',
      _req: null,
      [Symbol(kCapture)]: false
    },
    type: 'error',
    message: 'certificate has expired',
    error: Error: certificate has expired
        at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)
        at TLSSocket.emit (node:events:394:28)
        at TLSSocket.emit (node:domain:470:12)
        at TLSSocket._finishInit (node:_tls_wrap:944:8)
        at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)
        at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
      code: 'CERT_HAS_EXPIRED'
    }
  }
}
```
经查询，https证书到期时间是Wed, 05 Jan 2022 16:36:40 GMT，而且浏览器访问也没问题。

**Comment by Clansty** [comment]
@Dreagonmon 可以试试 caddy 反代

**Comment by Clansty** [comment]
@Dreagonmon 确实是这个原因，我九月底出现了，然后换亚洲诚信的证书就好了

**Comment by Dreagonmon** [comment]
换了证书能解决，确实是Let`s Encrypt的问题。

本地根证书是可用的，但是AppImage包内似乎没用到，而且环境变量NODE_TLS_REJECT_UNAUTHORIZED=0并不能忽略ssl证书验证。

估计用caddy自动申请的证书似乎也是Let`s Encrypt，也会出现同样的问题。有没有可能通过更新软件来支持Let`s Encrypt证书呢？或者至少更新一下Readme.md说明文件提示一下？

**Comment by Clansty** [comment]
@Dreagonmon 可以通过更换证书品牌解决，这应该是 node 的问题
