### ISSUE TITLE
请帮我看看我这个一直报无法连接数据库是什么问题

### ISSUE THREAD

**Issue by kero990** [Icalingua/Icalingua#313]
**Describe the bug / 描述**
使用内置数据库时登陆报“无法连接数据库”
**To Reproduce / 复现过程**
安装后一直无法使用，无论用uos源下载还是github下载的

**System information / 系统信息**
 arm64架构，飞腾处理器，uos系统

**终端输出
`$ /opt/Icalingua/icalingua
[24275:1105/161134.638034:ERROR:browser_main_loop.cc(269)] GLib-GObject: g_value_set_boxed: assertion 'G_VALUE_HOLDS_BOXED (value)' failed
[24309:1105/161134.951438:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
Cannot find an external media player
icalingua> (node:24275) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `icalingua --trace-warnings ...` to show where the warning was created)
Knex: run
$ npm install sqlite3 --save
/lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.org.chromium.Chromium.52I7b3)
Error: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.org.chromium.Chromium.52I7b3)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1800)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1170:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2027)
    at Module.load (node:internal/modules/cjs/loader:982:32)
    at Module._load (node:internal/modules/cjs/loader:823:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1006:19)                                   
    at require (node:internal/modules/cjs/helpers:93:18)                                           
    at Object.<anonymous> (/opt/Icalingua/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)                                                                                        
    at Module._compile (node:internal/modules/cjs/loader:1110:14)                                  
Error: Knex: run
$ npm install sqlite3 --save
/lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.org.chromium.Chromium.52I7b3)
    at Client_SQLite3.initializeDriver (/opt/Icalingua/resources/app.asar/node_modules/knex/lib/client.js:182:13)
    at new Client (/opt/Icalingua/resources/app.asar/node_modules/knex/lib/client.js:71:12)
    at new Client_SQLite3 (/opt/Icalingua/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:20:5)
    at Object.knex [as default] (/opt/Icalingua/resources/app.asar/node_modules/knex/lib/knex-builder/Knex.js:12:28)
    at new e (/opt/Icalingua/resources/app.asar/dist/electron/main.js:315:264327)
    at /opt/Icalingua/resources/app.asar/dist/electron/main.js:5:211895
    at /opt/Icalingua/resources/app.asar/dist/electron/main.js:5:199388
    at Object.next (/opt/Icalingua/resources/app.asar/dist/electron/main.js:5:199493)
    at /opt/Icalingua/resources/app.asar/dist/electron/main.js:5:198405
    at new Promise (<anonymous>)
(node:24275) UnhandledPromiseRejectionWarning: Error: ERR_FAILED (-2) loading 'file:///opt/Icalingua/resources/app.asar/dist/electron/index.html#/main'
    at rejectAndCleanup (node:electron/js2c/browser_init:165:7486)
    at Object.stopLoadingListener (node:electron/js2c/browser_init:165:7861)
    at Object.emit (node:events:394:28)
    at Object.emit (node:domain:470:12)
    at Object.topLevelDomainCallback (node:domain:147:15)
    at Object.callbackTrampoline (node:internal/async_hooks:128:24)
(node:24275) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
`

**Comment by sukanka** [comment]
猜是glibc太老了，建议drop support.

**Comment by kero990** [comment]
嗯，uos的包的确都非常之老，而且还不能随便更新。
ldd (Debian GLIBC 2.28.14-1+dde) 2.28,目前是这样
