### ISSUE TITLE
2.3.2 Loongarch专版使用问题

### ISSUE THREAD

**Issue by kanuchang** [Icalingua/Icalingua#318]
Describe the bug / 描述
使用内置SQLite数据库时登陆报“无法连接数据库”，尝试了内置中所有的数据库类型，MongoDB、Redis、MySQL/MariaDB、PostgreSQL等都能正常打开界面，但从通讯录中选择打开聊天窗口后，一直在转圈，尝试发送表情或简单文字信息是成功的，但发送图片或者接收文件都会导致程序中断退出。

**终端输出
使用内置SQLite数据库一直无法连接，我是在github下载2.2.4及2.3.2并解压覆盖打开的
尝试在终端窗口使用npm命令安装SQlite3，一直有如下报错
user@uos-PC:~/Downloads/icalingua$ npm install sqlite3 --save
Error: Cannot find module 'json-parse-even-better-errors'
Require stack:
- /usr/share/nodejs/npm/node_modules/read-package-json-fast/index.js
- /usr/share/nodejs/npm/node_modules/pacote/lib/file.js
- /usr/share/nodejs/npm/node_modules/pacote/lib/git.js
- /usr/share/nodejs/npm/node_modules/pacote/lib/fetcher.js
- /usr/share/nodejs/npm/node_modules/pacote/lib/index.js
- /usr/share/nodejs/npm/lib/utils/update-notifier.js
- /usr/share/nodejs/npm/lib/cli.js
- /usr/share/nodejs/npm/bin/npm-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/share/nodejs/npm/node_modules/read-package-json-fast/index.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/share/nodejs/npm/node_modules/pacote/lib/file.js:5:25)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
/usr/share/nodejs/@npmcli/config/lib/index.js:163
      throw new Error('call config.load() before reading values')
      ^

Error: call config.load() before reading values
    at Config.get (/usr/share/nodejs/@npmcli/config/lib/index.js:163:13)
    at process.errorHandler (/usr/share/nodejs/npm/lib/utils/error-handler.js:171:32)
    at process.emit (events.js:315:20)
    at process._fatalException (internal/process/execution.js:163:25)
user@uos-PC:~/Downloads/icalingua$ 

System information / 系统信息
loongarch64架构，Loongson-3A5000LL处理器，统信uos系统

**Comment by sukanka** [comment]
参考 http://bbs.loongnix.cn/d/16/11

**Comment by kanuchang** [comment]
> 参考 http://bbs.loongnix.cn/d/16/11

谢谢，我下载了楼主打的包并解压安装到了根目录，可以启动成功，终于可以接受文字消息和文件了。但是仍然不能发送图片，一旦尝试发送，会出现WebSocket Error，不知道如何解决
![未命名](https://user-images.githubusercontent.com/19322162/141073074-457c3f82-bec9-4380-a50d-295f0132029f.jpg)
？

**Comment by sukanka** [comment]
@kanuchang, 2.4.0版本可以发送图片了。https://github.com/Icalingua/Icalingua/releases
