### ISSUE TITLE
[BUG]使用中继服务后，在客户端内复制图片后发送会导致服务端崩溃。

### ISSUE THREAD

**Issue by aimerneige** [Icalingua/Icalingua#393]
**Describe the bug / 描述**
A clear and concise description of what the bug is. / 请简要描述出现的 bug

使用中继服务后，在客户端内复制图片后发送会导致服务端崩溃。具体表先为图片以 base64 格式发送，服务器尝试拉取消息时会造成 JSON 解析错误。

**To Reproduce / 复现过程**

**Expected behavior / 预期的结果**

**Screenshots / 截图**
If applicable, add screenshots to help explain your problem. / 如果可能的话，请附上相关截图

![image](https://user-images.githubusercontent.com/51701792/147840254-c8c7c058-d6ec-4f2b-9f98-b8d34cca0300.png)

![image](https://user-images.githubusercontent.com/51701792/147840261-cfd21ed2-b332-4ba9-9458-2548e13a041d.png)

![image](https://user-images.githubusercontent.com/51701792/147840320-f829cd6c-bd56-48f2-9ae0-f946d803e6cc.png)

**System information / 系统信息**
 - 中继服务器OS: Ubuntu 20.04.3 LTS x86_64
 - 中继服务器Version: Dev 分支 [03cbfb0cd7c2642eb166280d098e86d44b9a037c](https://github.com/Icalingua/Icalingua/commit/03cbfb0cd7c2642eb166280d098e86d44b9a037c)
- 客户端OS: Pop!_OS 21.04 x86_64
- 客户端版本: v2.4.5

**Additional context / 附加信息**
Add any other context about the problem here. / 如果有什么额外信息，可以写在这里

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at SQLStorageProvider.msgConFromDB (/home/ubuntu/Icalingua/newest/icalingua-bridge-oicq/build/storageProviders/SQLStorageProvider.js:99:143)
    at /home/ubuntu/Icalingua/newest/icalingua-bridge-oicq/build/storageProviders/SQLStorageProvider.js:424:61
    at Array.map (<anonymous>)
    at SQLStorageProvider.fetchMessages (/home/ubuntu/Icalingua/newest/icalingua-bridge-oicq/build/storageProviders/SQLStorageProvider.js:424:39)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.fetchMessages (/home/ubuntu/Icalingua/newest/icalingua-bridge-oicq/build/adapters/oicqAdapter.js:877:27)
```

**Comment by lixiang810** [comment]
@aimerneige 一周后我会d8g一下，预计从现在开始的两周内能修复

**Comment by qndydyhm** [comment]
我这里好像根本就无法复制

**Comment by qndydyhm** [comment]
遇到了好几次类似的问题，但是不是和复制有关，不过每次好像都和图片相关，原因不明，不知道如何复现
