### ISSUE TITLE
[BUG]无法连接postgresql数据库

### ISSUE THREAD

**Issue by wuweilin99** [Icalingua/Icalingua#395]
**Describe the bug / 描述**
使用docker的postgresql数据库，版本为13，连接时候提示无法连接，使用dbeaver与pgadmin测试可以正常连接

**Screenshots / 截图**
![Uploading image.png…]()

icalingua> (node:51502) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `icalingua --trace-warnings ...` to show where the warning was created)
Error: getaddrinfo ENOTFOUND 127.0.0.1:65430
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
    at GetAddrInfoReqWrap.callbackTrampoline (internal/async_hooks.js:131:14) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: '127.0.0.1:65430'
}
(node:51502) UnhandledPromiseRejectionWarning: Error: ERR_FAILED (-2) loading 'file:///tmp/.mount_IcalinKHLodD/resources/app.asar/dist/electron/index.html#/main'
    at rejectAndCleanup (electron/js2c/browser_init.js:213:985)
    at Object.stopLoadingListener (electron/js2c/browser_init.js:213:1360)
    at Object.emit (events.js:315:20)
    at Object.EventEmitter.emit (domain.js:467:12)
    at Object.topLevelDomainCallback (domain.js:144:15)
    at Object.callbackTrampoline (internal/async_hooks.js:129:14)
(node:51502) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:51502) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
**System information / 系统信息**
 - OS: [Arch Linux]
 - Icalingua.version：2.4.5
 - postgressql:13

**Comment by lixiang810** [comment]
@wuweilin99 你是自己电脑开的pgsql，所以可以把tls关掉

**Comment by wuweilin99** [comment]
@lixiang810 您好，我看了一下我的数据库并没有开启tls，那个只是一个警告吧？

**Comment by lixiang810** [comment]
@wuweilin99 尝试使用默认端口看看

**Comment by wuweilin99** [comment]
@lixiang810 我原来用的就是默认端口，也不行，后面才改的其他端口

**Comment by lixiang810** [comment]
默认端口的时候不加端口号看看

**Comment by lixiang810** [comment]
注意到你是 ArchLinux，可以额外检查一下 `/etc/hosts` 和 `/etc/hostname` 有没有配置好。
https://wiki.archlinux.org/title/Installation_guide_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)

**Comment by wuweilin99** [comment]
@lixiang810 我使用默认端口不加端口号的时候登录，那这个是我端口的写法有问题吗？

**Comment by lixiang810** [comment]
可以认为加上端口号就无法使用是一个 bug。我会在大约一周之内检查并修复。
