### ISSUE TITLE
[BUG]engine为内置SQLite时无法连接到数据库

### ISSUE THREAD

**Issue by 123ABCDF11345** [Icalingua/Icalingua#420]
### 复现流程
![图片](https://user-images.githubusercontent.com/50321657/150624895-a152f0d3-93b2-4e41-a410-e60da3da7c35.png)
如图配置（qq号已改），点击login弹出无法连接到数据库

### 系统环境
Debian 10 ARM64

### 技术信息
我已经看了 #212 但是这个是内置数据库，不应该报错啊?需要我自己安装sqlite吗？ 使用deb包安装的

日志如下
```
icalingua> (node:8610) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `icalingua --trace-warnings ...` to show where the warning was created)
Knex: run
$ npm install sqlite3 --save
/lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.org.chromium.Chromium.Qbc6Bl)
Error: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.org.chromium.Chromium.Qbc6Bl)
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/opt/Icalingua/resources/app.asar/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
Error: Knex: run
$ npm install sqlite3 --save
/lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.org.chromium.Chromium.Qbc6Bl)
    at Client_SQLite3.initializeDriver (/opt/Icalingua/resources/app.asar/node_modules/knex/lib/client.js:182:13)
    at new Client (/opt/Icalingua/resources/app.asar/node_modules/knex/lib/client.js:71:12)
    at new Client_SQLite3 (/opt/Icalingua/resources/app.asar/node_modules/knex/lib/dialects/sqlite3/index.js:20:5)
    at Object.knex [as default] (/opt/Icalingua/resources/app.asar/node_modules/knex/lib/knex-builder/Knex.js:12:28)
    at new e (/opt/Icalingua/resources/app.asar/dist/electron/main.js:315:267416)
    at /opt/Icalingua/resources/app.asar/dist/electron/main.js:5:104403
    at /opt/Icalingua/resources/app.asar/dist/electron/main.js:5:91937
    at Object.next (/opt/Icalingua/resources/app.asar/dist/electron/main.js:5:92042)
    at /opt/Icalingua/resources/app.asar/dist/electron/main.js:5:90954
    at new Promise (<anonymous>)
(node:8610) UnhandledPromiseRejectionWarning: Error: ERR_FAILED (-2) loading 'file:///opt/Icalingua/resources/app.asar/dist/electron/index.html#/main'
    at rejectAndCleanup (electron/js2c/browser_init.js:213:985)
    at Object.stopLoadingListener (electron/js2c/browser_init.js:213:1360)
    at Object.emit (events.js:315:20)
    at Object.EventEmitter.emit (domain.js:467:12)
    at Object.topLevelDomainCallback (domain.js:144:15)
    at Object.callbackTrampoline (internal/async_hooks.js:129:14)
(node:8610) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8610) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Clansty** [comment]
@123ABCDF11345 看一下 glibc 是不是版本不太对

**Comment by 123ABCDF11345** [comment]
@Clansty ldd (Debian GLIBC 2.28-10) 2.28

**Comment by 123ABCDF11345** [comment]
需要我更新到2.29吗

**Comment by lixiang810** [comment]
@123ABCDF11345 越新越好

**Comment by 123ABCDF11345** [comment]
@lixiang810 Emm，经历了多次系统崩溃后，我失败了。请问可以告知是哪个模块需要高版本的glibc吗，我试着降级自己编译下

**Comment by CoelacanthusHex** [comment]
@123ABCDF11345 sqlite

**Comment by 123ABCDF11345** [comment]
也就是说不用内置数据库就可以解决这个问题吗



------------------ 原始邮件 ------------------
发件人: Coelacanthus ***@***.***&gt;
发送时间: 2022年1月24日 19:35
收件人: Icalingua/Icalingua ***@***.***&gt;
抄送: Wang ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [Icalingua/Icalingua] [BUG]engine为内置SQLite时无法连接到数据库 (Issue #420)





 
@123ABCDF11345 sqlite

**Comment by 123ABCDF11345** [comment]
已使用外部数据库解决,close
